# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131bd1957e02edf548160c8bf176337f8ad1a20614e195099d239db36c4ce6c895c29c6a44dc2d136ff563fe4e452bab189b78a6ed806ccdcde019ba1af109b8

test:
  secret_key_base: 0eac62a1207b49f0cfee6025b1f1865bad626d2b4b18918ded44d60e393fb17a03bfc42c7b694569b294904d6c1c68df26c2b72b3bf3914af3f859ef074767d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
